step "welcome"
    reply "欢迎来到美味餐厅！🍽️"
    reply "我们可以为您提供："
    reply "1. 餐厅订位"
    reply "2. 菜单咨询" 
    reply "3. 特色菜品介绍"
    reply "4. 营业时间查询"
    reply "请问您需要什么服务？"
    wait "make_reservation" "menu_inquiry" "special_dishes" "business_hours" "unknown"

step "make_reservation"
    reply "很高兴为您安排订位！"
    reply "请问用餐人数是多少？"
    wait "select_people_number"

step "select_people_number"
    log "人数" + $user_input
    reply "已记录" + $user_input + "位用餐"
    reply "请选择用餐日期（例如：今天、明天、12月25日）："
    wait "select_time"

step "select_time"
    log "日期：" + $user_input
    reply "已记录日期：" + $user_input
    reply "请选择用餐时间（例如：18:00、晚上7点）："
    wait "confirm_reservation"

step "confirm_reservation"
    log "时间：" + $user_input
    reply "已记录时间：" + $user_input
    reply "请提供订位人姓名和联系电话："
    wait "reservation_complete"

step "reservation_complete"
    reply "姓名和联系电话：" + $user_input
    reply "预订成功！✅"
    reply "我们会提前15分钟与您确认，期待您的光临！"
    wait "welcome" "menu_inquiry" "special_dishes" "business_hours" "thankyou"

step "menu_inquiry"
    reply "这是我们的菜单："
    reply "🍽️ 前菜："
    reply "- 凯撒沙拉 ￥48"
    reply "- 法式鹅肝 ￥128"
    reply "🍖 主菜："
    reply "- 澳洲牛排 ￥298"
    reply "- 意大利面 ￥88"
    reply "- 烤三文鱼 ￥158"
    reply "🍰 甜点："
    reply "- 提拉米苏 ￥58"
    reply "- 巧克力熔岩 ￥68"
    reply "需要了解哪道菜的详细信息吗？"
    wait "dish_detail" "make_reservation" "welcome" "thankyou"

step "dish_detail"
    reply "为您介绍" + $user_input + "："
    reply "这道菜选用最新鲜的食材，由我们主厨精心烹制。"
    reply "需要为您预订品尝吗？"
    wait "make_reservation" "menu_inquiry" "welcome" "thankyou"

step "special_dishes"
    reply "本周特色菜品："
    reply "🌟 主厨推荐：黑松露牛排 ￥358"
    reply "🌟 季节限定：秋季松茸套餐 ￥458/位"
    reply "🌟 海鲜特选：法式龙虾 ￥588"
    reply "这些菜品都需要提前预订，您感兴趣吗？"
    wait "make_reservation" "menu_inquiry" "welcome" "thankyou"

step "business_hours"
    reply "营业时间："
    reply "⏰ 周一至周五：11:00-14:00, 17:00-22:00"
    reply "⏰ 周六周日：11:00-23:00"
    reply "📍 地址：市中心美食街88号"
    reply "📞 电话：400-123-4567"
    reply "需要为您预订位子吗？"
    wait "make_reservation" "welcome" "thankyou"

step "thankyou"
    reply "感谢您的咨询！"
    reply "期待为您服务，祝您用餐愉快！😊"
    wait "welcome" "make_reservation" "menu_inquiry" "special_dishes" "business_hours"

step "unknown"
    reply "抱歉，我没有完全理解您的需求。"
    reply "我们可以为您提供："
    reply "1. 餐厅订位"
    reply "2. 菜单咨询"
    reply "3. 特色菜品介绍" 
    reply "4. 营业时间查询"
    reply "请问您需要哪项服务？"
    wait "make_reservation" "menu_inquiry" "special_dishes" "business_hours" "welcome"